config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  get "tops/index", to: "tops#index"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :feeds do
    collection do
      post:confirm
    end
  end
  resources :favorites, only: [:create, :index, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user 
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true,
                    uniqueness: true,
                    length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation{ email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  has_many :feeds
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入りしました"
  end

  def index
    @favorites = Favorite.all
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿を解除しました"
　end
end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :check_logged_in, only:[:new]
  before_action :set_feed, only:[:show,:edit,:update,:destroy]
  before_action :check_correct_user, only:[:edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user = current_user
    if @feed.save
      ContactMailer.contact_mail(@feed).deliver
      redirect_to feeds_path, notice:"投稿完了"
    else
      render "new"
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def edit
  end

  def update
    if @feed.update(feed_params)
      redirect_to feeds_path, notice: "編集完了"
    else
      render "edit"
    end
  end

  def destroy
    @feed.destroy
    redirect_to feeds_path, notice:"削除完了"
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end

  def check_correct_user
    if current_user != @feed.user
      redirect_to new_session_path
    end
  end

  def check_logged_in
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
   session.delete(:user_id)
   redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private

  def login
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_feeds_path
    elsif action_name == "edit"
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_users_path
    elsif action_name == "edit"
      user_path
    end
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<% @favorites.each do |favorite| %>
  <%= image_tag(favorite.feed.image.url) if favorite.feed.image.url %><br>
<% end %>

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if @feed.errors.any? %>
    <div id ="error_explanation">
      <h2><%= @feed.errors.count %>件のエラーがあります。_form.html.erb</h2>
      <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :写真 %><br>
    <%= image_tag(@feed.image.url) if @feed.image.url %><br>
    <div class = "center_image_post">
      <%= form.file_field :image %><br>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.label :文章 %><br>
    <%= form.text_field :content%><br>
    <%= form.submit %><br>

<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>

<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>

  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>

  <P>写真<br><%= image_tag(@feed.image.url) if @feed.image.url %></p>
  <p>文章<br><%= @feed.content %></p>
  <%= form.submit "登録" %>
<% end %>

<%= form_with(model: @feed, url: new_feed_path,local: true, method: "get") do |form| %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>編集する</h1>
<%= render 'form' %>
<%= link_to "戻る", feed_path(@feed.id) %>

app/views/feeds/index.html.erb
<h1>一覧</h1>
<%= notice %><br>
<%= link_to "投稿する", new_feed_path %>

<div class="container">
<ul class="row">
  <% @feeds.each do |feed| %>
    <li class = "col-md-4"><%= link_to "詳細", feed_path(feed.id) %></li>
    <% if feed.image.url %>
      <li class = "col-md-4"><%= image_tag(feed.image.url) %></li>
    <% end %>
  <% end %>
</ul>
</div>

app/views/feeds/new.html.erb
<h1>投稿する</h1>
<%= render 'form' %>

app/views/feeds/show.html.erb
<h1>詳細</h1>
<%= image_tag(@feed.user.image.url) if @feed.user.image %><%= @feed.user.name %>
<p>写真<br><%= image_tag @feed.image.url %></p>
<P>文章<br> <%= @feed.content %></p>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to "お気に入り解除する", favorite_path(id: @favorite.id), method: :delete, class: "btn btn-danger" %>
  <% else %>
    <%= link_to "お気に入りする", favorites_path(feed_id: @feed.id), method: :post, class: "btn btn-primary" %>
  <% end %>
<% end %>

<% if current_user == @feed.user %>
  <%= link_to '編集', edit_feed_path(@feed.id) %>
  <%= link_to "削除", feed_path(@feed.id), method: :delete, data:{confirm: "本当に？"} %>
<% end %>
<%= link_to '戻る', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExam3</title>
    <meta name = "viewport" content="width=device-width">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=“#gnavi">
          <span class=“sr-only"></span>
          <span class=“icon-bar”></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand"><%= link_to "I○stagram", tops_index_path,class: "home" %></a>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if logged_in? %>
            <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
            <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% else %>
            <li><%= link_to "新規登録", new_user_path %></li>
            <li><%= link_to "ログイン", new_session_path %></li>
          <% end %>
          <% if logged_in? %>
            <li><%= link_to "投稿一覧", feeds_path %></li>
            <li><%= link_to "新規投稿", new_feed_path %></li>
            <li><%= link_to "ユーザー一覧", users_path %></li>
            <li><%= link_to "お気に入り一覧",favorites_path(current_user.id) if current_user %></li>
          <% end %>
        </ul>
      </div>
    </div>
    </nav>
    <div class="container">
      <div class = "center">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
      <footer class="footer">
      </footer>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: user_choose_new_or_edit) do |f| %>
  <% if @user.errors.any? %>
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>
  <%= f.label :写真 %><br>
  <div class = "center_image_post">
    <%= f.file_field :image %><br>
  </div>
  <%= f.label :名前 %><br>
  <%= f.text_field :name %><br>
  <%= f.label :メールアドレス %><br>
  <%= f.email_field :email %><br>
  <%= f.label :パスワード %><br>
  <%= f.password_field :password %><br>
  <%= f.label :パスワード再確認 %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit %><br>
<% end %>

app/views/users/edit.html.erb
<h1>編集する</h1>
<%= render "form" %>
<%= link_to "詳細に戻る", user_path(@user.id) %>

app/views/users/index.html.erb
<p>ユーザー一覧</p>
<% @users.each do |user| %><br>
<%= image_tag user.image.url %><br>
<%= link_to user.name, user_path(user.id) %><br>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<% if @user.errors.any? %>
  <div id=“error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %>
　　　　　　　　　　　　　　　　　prohibited this @user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :名前 %><br>
  <%= f.text_field :name %><br>

  <%= f.label :メールアドレス %><br>
  <%= f.email_field :email %><br>

  <%= f.label :パスワード %><br>
  <%= f.password_field :password %><br>

  <%= f.label :パスワード再確認 %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "新規登録" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<%= notice %>
<%= image_tag @user.image.url %><br>
<p>メールアドレス</p><br>
<%= @user.email %><br>
<%= link_to "編集", edit_user_path(@user.id) %>
<%= link_to "戻る", users_path %>